# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5c6ec30d82d465bcc1fc275566b8586055e1af83e7e2f68f9a004a7f7544455d2102c4d62359c929ba8bd494562c5557fcbc94803d36dd211a99984787a1c15

test:
  secret_key_base: 62e8e6c9b135d438d884889f0c77c0fae3a15a70cee0dad86167a0e7366fe576115e6e4900d747e6d476f3ece9cfbf9750857ad643f1a15c47e44c0597b577b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
